image:
    file: .gitpod.dockerfile
tasks:
    - init: >
        git clone https://github.com/emscripten-core/emsdk.git
        && cd emsdk
        && ./emsdk install latest
        && ./emsdk activate latest
        && . ./emsdk_env.sh
        && cd ..